### 넘파이 배열
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모리 차지의 문제를 해결하고자 수치 해석 프로그램에서는 numpy라고하는 배열 패키지를 사용함
numpy 배열의 경우 자체적 C언어로 구현되어 있어 자료형 지정과 메모리 절약효과를 볼 수 있음

### NumPy import
numpy 패키지를 사용하려면 먼저 패키지를 설치해야 함
```bash
pip install numpy(터미널에 입력하면 됨)
```  
numpy 패키지를 프로그램에서 사용하려면 import 해야 함
```python
import numpy
import numpy as np
```

In [184]:
import numpy as np

### 1차원 배열 만들기
넘파이의 `array` 함수를 사용하여 리스트를`ndarray` 타입으로 변경 가능

In [185]:
ndarray_= np.array([0, 1, 2, 3, 4])
ndarray_

array([0, 1, 2, 3, 4])

In [186]:
type(ndarray_)

numpy.ndarray

In [187]:
floats = np.array([1.0, 2.0, 3.0, 4.0])
floats

array([1., 2., 3., 4.])

In [188]:
floats = np.array([0.1, 0.2, 0.3, 0.4])
floats

array([0.1, 0.2, 0.3, 0.4])

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함  
이러한 numpy 배열의 특성 때문에 특정 요소에 대한 접근 속도가 빠름

In [189]:
ndarray_ = np.array([1, 1.5, 2])  # 넘파이 배열의 요소는 타입이 모두 동일해야 하므로 1.5 실수로 인해 1, 2가 실수로 변함.
ndarray_

array([1. , 1.5, 2. ])

In [190]:
ndarray_ = np.array(['문자열', 1, 1.5]) # '문자열'에 인해 1, 1.5가 문자열 타입으로 변경됨.
ndarray_            # U = 유니코드, 하나의 영문, 문자에 하나의 코드값을 가진다.(모든 자바 문자는 고유?의 코드값을 가지고 있다.)

array(['문자열', '1', '1.5'], dtype='<U32')

### 벡터화 연산
numpy 배열은 각 원소에 대한 반복 연산을 간단한 명령으로 처리할 수 있는 벡터화 연산을 지원

In [191]:
# 각 요소를 2씩 곱하는 연산
# 리스트를 사용했을 때
numbers = list(range(10))   # range는 -1만큼까지 출력된다.(0부터)
result = []
for number in numbers:
    result.append(number * 2)

result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [192]:
# numpy array를 사용할 때
numpy_numbers = np.array(numbers)
result = 2 * numpy_numbers
result

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [193]:
result = 2 * numbers    # 배열의 값이 * 2 연산되는 것이 아닌 배열 객체 자체가 2배가 되는것이므로
result                              #  배열이 중복되어 하나 더 나타난다고 보면 된다.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능

In [194]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5, 10)))

numbers1, numbers2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [195]:
result = numbers1 * 5 + numbers2
result

array([ 5, 11, 17, 23, 29])

In [196]:
result = numbers1 == 3
result

array([False, False, False,  True, False])

In [197]:
result = (numbers1 > 2) & (numbers2 < 10)
result

numbers1 >2, numbers2<10, result

(array([False, False, False,  True,  True]),
 array([ True,  True,  True,  True,  True]),
 array([False, False, False,  True,  True]))

### 2차원 배열
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 `array()`의 매개변수로 전달하면 2차원 배열을 생성할 수 있음

In [198]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7,  8, 9]
    ]
numpy_matrix = np.array(matrix)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [199]:
len(numpy_matrix)

3

In [200]:
numpy_matrix[0]

array([1, 2, 3])

In [201]:
len(numpy_matrix[0])

3

### 3차원 배열 만들기
리스트의 요소로 2차원 형태를 띄는 리스트를 지정하면 3차원 배열로 만들 수 있음

In [202]:
three_d = [
    [
        [1, 2, 3, 4,],
        [5, 6, 7, 8,],
        [9, 10, 11, 12, ]
    ],
    [
        [13, 14 ,15 ,16],
        [17, 18, 19, 20,],
        [21, 22, 23, 24]
    ]
]
numpy_three_d = np.array(three_d)
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### 배열의 차원과 크기 구하기
`ndim()`: 배열의 차원을 정수로 반환  
`shape`: 배열의 각 차원의 크기를 정수의 튜플로 반환

In [203]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [204]:
print(numpy_matrix.ndim),#  (ndim의 뜻은 해당 배열이 1차원 배열인지, 2차원 배열인지의 그 크기를 구하는 것)
numpy_matrix.shape  #(shape 행열을 뜻함, numpy_matrix는 3행3열이므로 (3, 3)이 나옴

2


(3, 3)

In [205]:
numpy_three_d.ndim, numpy_three_d.shape

(3, (2, 3, 4))

### numpy 백열의 인덱싱
일반적으로 `배열변수 [인덱스]`의 형태로 사용함  
다차원 형태일 경우는 일반 리스트와 다르게 `배열변수[인덱스, 인덱스, ...]`의 형태로 사용함  
일반 2차원 리스트: `리스트[인덱스][인덱스]`  
numpy 2차원 배열: `배열[인덱스, 인덱스]`

In [206]:
# 일반 3차원 리스트
three_d

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [207]:
three_d[1][0][3]    # three_d의 인덱스중에 16을 찾는 방법

16

In [208]:
# numpy 3차원 배열
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [209]:
numpy_three_d[1][0][3]  # numpy_three_d 에서 16을 찾는 방법

16

### numpy 배열 슬라이싱
일반 리스트에서 사용하는 배열 슬라이싱 방법, `리스트[시작인덱스:종료인덱스]`와 동일함  
단, 다차원 배열의 경우 인덱스를 여러개 지정할 때 `,`를 써야하는 것을 주의

In [210]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [211]:
numpy_matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [212]:
numpy_matrix[2]

array([7, 8, 9])

In [213]:
numpy_matrix[3:]

array([], shape=(0, 3), dtype=int32)

In [214]:
numpy_matrix[0,:2]

array([1, 2])

In [215]:
numpy_matrix[:2, 0]

array([1, 4])

In [216]:
numpy_matrix[1:, 1:]        # 행열을 나타내는 수의 뒤에 ' : '  가 있으면 해당 행,열로부터 끝까지 라는 뜻.
                                           # 1: 은 까지라고 보면되고, :1 은 부터라고 보면 된다.

array([[5, 6],
       [8, 9]])

In [217]:
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [218]:
numpy_three_d[:1]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [219]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
m
# 이 행렬에서 값 7 을 인덱싱한다.
# 이 행렬에서 값 14 을 인덱싱한다.
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [220]:
numpy_m = np.array(m)
numpy_m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [221]:
print(numpy_m[1, 2])
numpy_m[2, 4]   # [-1, -1] 도 가능

7


14

In [222]:
numpy_m[1, 1:3]     # 1번 인덱스에 있는 값에서, 1번부터 3번까지의 값을 가져와라.

array([6, 7])

In [223]:
numpy_m[1:, 2]  # 1번인덱스부터 끝까지 가져오고, 그 중에서 2번 열을 가져와라.

array([ 7, 12])

In [224]:
numpy_m[:2, 3:]     # [:2, 3:5]도 가능.

array([[3, 4],
       [8, 9]])

### 배열 인덱싱
**팬시 인덱싱(fancy indexing)** 이라고 부르는 배열 인덱싱 기법을 존재함  
이 배열 인덱싱은 인덱스로 정수 형태나 슬라이스 형태로 인덱스를 전달하는 게 아니라  
인덱스로 또 다른 넘파이 배열을 전달하여 그에 부합하는 새로운 배열을 반환

### 불리언 배열 인덱싱
`True`, `False` 두 형태로만 이루어진 배열을 인덱스로 전달하여 `True` 가 위치한 값만 반환하여 새로운 배열을 만드는 인덱싱 기법  
불리언 배열 인덱싱 기법은 기존 배열과 인덱스로 전달하는 배열의 크기가 같아야 한다.

In [225]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
index_array = np.array([True, True, False, False, False, True, True, True])
numpy_array[index_array]

array([1, 2, 6, 7, 8])

조건 연산을 통해서도 불리언 인덱싱 처리를 할 수 있음

In [226]:
numpy_array % 2

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [227]:
numpy_array % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [228]:
numpy_array[numpy_array % 2==0]

array([2, 4, 6, 8])

### 정수 배열 인덱싱
인덱스 배열의 원소의 값이 기존 넘파이 배열의 원소의 인덱스를 가리키는 정수로 구성된  배열을 인덱스로  
전달하여 해당하는 인덱스의 값들로 새로운 배열을 반환하는 기법

In [229]:
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [230]:
index_array = np.array([0, 2, 3])

In [231]:
numpy_array[index_array]

array([1, 3, 4])

인덱스 배열로 사용되는 정수 배열은 기존 배열의 길이보다 커도 사용 가능  
이때, 반환되는 배열의 길이는 인덱스 배열로 전달한 배열의 길이로 결정이 됨

인덱스 배열로 사용되는 정수 배열은 요소는 기존 배열의 최대 인덱스 범위를 벗어나는 값이 존재하는 경우
예외가 발생함

In [232]:
index_array = np.array([0, 2, 3, 6, 0, 2, 3, 6, 0, 2, 3, 6])

In [233]:
numpy_array[index_array]

array([1, 3, 4, 7, 1, 3, 4, 7, 1, 3, 4, 7])

#### 다차원 배열에서 배열 인덱싱

In [234]:
index_array = np.array([True, False, True])
numpy_matrix[:2, index_array]

array([[1, 3],
       [4, 6]])

In [235]:
# 배열 인덱스 값으로 정수 리스트를 전달하면 리스트의 배열의 순서가 변경 됨
numpy_matrix[[2, 1, 0], :]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

#### 파이썬으로 다음 연산을 수행한다.
다음 행렬과 같은 배열이 있다.

```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```
1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.


In [236]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
#1
np.array(x)
print(x[x % 3 == 0])
#2
print(x[x % 4 == 1])
#3
print(x[(x % 3 == 0) & (x % 4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


### numpy 배열의 자료형
numpy 배열의 원소는 모두 같은 데이터 타입을 가지고 있음
numpy 배열의 데이터 타입을 확인하고자 한다면 `dtype`속성으로 확인이 가능

In [237]:
numpy_array = np.array([1, 2, 3])
numpy_array.dtype

dtype('int32')

In [238]:
numpy_array = np.array([1.0, 2.0, 3.0])
numpy_array.dtype

dtype('float64')

In [239]:
numpy_array = np.array(['1.0', '2.0', '3.0'])
numpy_array.dtype   # 길이가 3짜리인 문자열.

dtype('<U3')

`array()` 함수를 사용하여 배열을 생성할 때 명시적으로 데이터 타입을 지정하지 않으면 자동으로 데이터 타입을 추론하여 지정하게 됨  
만약, 명시적으로 데이터 타입을 지정하고자 한다면 `array()` 함수에 `dtype` 매개변수로 데이터 타입을 지정해주면 됨

##### dtype의 접두사
b: 불리언, i: 정수, f: 실수, U: 유니코드

In [240]:
numpy_array = np.array(['1.0', '2.0', '3.0'], dtype='f')
numpy_array.dtype

dtype('float32')

In [241]:
numpy_array

array([1., 2., 3.], dtype=float32)

### numpy에서 Inf와 NaN
numpy 배열 연산에서 1을 0으로 나누면 `inf`, -1을 0으로 나누면 `-inf`, 0을 0으로 나누면 `nan`이 반환됨

### 배열 생성
numpy 배열을 생성하는 방법  
- `zeros`, `ones`  
- `zeros_like`, `ones_like`  
- `empty`  
- `arange`  
- `linspace`, `logspace`

#### zeros
크기가 정해져 있고 원소를 0으로 초기화한 배열을 생성하는 함수

In [242]:
numpy_array = np.zeros(5)
numpy_array

array([0., 0., 0., 0., 0.])

In [243]:
# 매개변수로 정수 튜플을 전달하여 다차원 배열 생성도 가능
numpy_array = np.zeros((2, 3))  # 2행 3열의 배열 생성
numpy_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [244]:
# dtype을 명시하여 데이터타입을 지정할 수 있음
numpy_array = np.zeros((2, 3),dtype = 'i')
numpy_array

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

만약, dtype으로 문자열 (U)로 지정하게되면 문자열의 길이가 초과하면 초과된 부분이 손실됨

#### ones
크기가 정해져 있고 원소를 1로 초기화한 배열을 생성하는 함수  
`zeros`함수와 사용법이 동일

In [245]:
ones_array = np.ones((3, 2, 2), dtype = 'i')
ones_array

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

#### zeros_like, ones_like
크기를 직접 지정하지 않고 이미 존재하는 배열의 크기를 본따서 0 또는 1로 채워진 배열을 생성하는 함수

In [246]:
zeros_array = np.zeros_like(ones_array, dtype = 'f')
zeros_array

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)

#### empty
크기만 지정하고 원소의 값은 `쓰레기 데이터`로 채워진 배열을 생성  
`zeros`, `ones` 함수를 사용하여 배열을 생성하는 것보다 배열 생성 속도가 빠름  

In [247]:
empty_array = np.empty((10, 10))
empty_array

array([[7.26607951e+223, 6.10941618e+223, 1.28012645e-152,
        3.68776644e+180, 1.38692357e+219, 1.81645702e+223,
        8.88968953e+228, 6.01347002e-154, 9.29603063e+199,
        6.07850020e+247],
       [3.62479380e+228, 6.19180686e+223, 4.74340791e+164,
        8.56232545e+194, 2.31261077e-152, 2.45066353e+198,
        6.01347002e-154, 3.62479380e+228, 2.64521689e+185,
        5.98150355e-154],
       [1.67772062e+243, 3.68727164e+180, 9.77824555e+199,
        6.01334653e-154, 1.32971156e-152, 1.46915533e+195,
        1.27919412e-152, 3.09391800e+169, 3.29216432e+180,
        4.83245960e+276],
       [5.30886249e+180, 5.83439495e+252, 2.46598536e-154,
        1.91002772e+227, 8.67185941e+199, 3.94645963e+180,
        5.25185407e+170, 1.06263900e+248, 1.09944918e+155,
        1.17072865e+214],
       [5.80426330e+180, 9.29603063e+199, 6.01334519e-154,
        1.67494802e+243, 5.17086021e+170, 3.67289399e+194,
        6.52022889e+252, 3.98837335e+252, 3.10868867e+169,
        2.6

#### arange
파이썬의 내장함수 `range()` 함수의 동일한 기능을 하는 numpy배열 생성 함수  

In [248]:
arage_array = np.arange(10, 50, 1)
arage_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [249]:
arage_array = np.arange(50, 10, -1)
arage_array

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11])

#### 전치 연산
배열의 행과 열의 위치를 전치시키는 방법 배열의`T`속성으로 반환 받을 수 있음  

In [250]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [251]:
numpy_matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [252]:
numpy_three_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [253]:
numpy_three_d.T     # 2, 3, 4 -> 4, 3, 2

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

### 배열의 크기 변경
numpy 배열에서 원소의 개수를 유지한 상태로 배열의 형태의 변경하려 한다면 `reshape` 메서드를 사용하여 변경할 수 있음  
홀수는 에러뜸.

In [254]:
numpy_array = np.zeros(12)      # zeros= 0. 으로 초기화.
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [255]:
reshape_array = numpy_array.reshape(4, 3)   # 위에서 12개의 0.이 1차원배열로 생성이 됬는데, reshape(4, 3)으로 인해
reshape_array                                                       # 4행 3열 2차원 배열로 변경됨

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [256]:
reshape_array = numpy_array.reshape(2, 6)
reshape_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [257]:
reshape_array = numpy_array.reshape(4, 3)
reshape_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

numpy 배열의 원소는 개수가 정해져 있기 때문에 `reshape` 메서드에 하나의 인자로 -1을 넣게 되면  
다른 인자들을 통해서 추론하여 지정

In [258]:
reshape_array = numpy_array.reshape(6, -1)  # 총 12개의 0. 1차 배열에서 reshape(6, -1)이므로, 6은 6행이니까 6개의 행이 생성됨,
reshape_array                                                       #  열의 위치의 수가 미지수 거나, -1을 넣게 되면, 6개의 행이 생성이 되도록 추론하여 들어가진다.

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [259]:
reshape_array = numpy_array.reshape(3, 1, -1)
reshape_array

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

만약 `reshape` 메서드의 인자들의 곱의 결과가 기존 배열의 원소의 총 합과 다르면 에러가 발생  
-1로 지정한 인자가 있을 때 해당 인자의 곱으로 총합을 계싼할 수 없는 경우면 에러가 발생

다차원 배열을 무조건 1차원 배열로 변경하려 한다면 `flatten`이나 `ravel`메서드를 사용함

In [260]:
numpy_matrix = np.empty((3, 4))
numpy_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [261]:
numpy_array = numpy_matrix.flatten()
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [262]:
numpy_array = numpy_matrix.ravel()
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

배열 사용에서 주의할 점은 * 길이가 5인 1차원 배열 * 과 *5x1인 2차원 배열*, *1x5인 2차원 배열*은 서로 각각 다른 배열이다.  
요소의 개수와 내용, 순서가 모두 같더라도 형태가 다르면 다른 배열이다.

차원을 한 차원 증가시키고자 한다면 `numpy.newaxis`속성으로 차원을 증가 시킬 수 있음

In [263]:
newaxis_array = numpy_array[np.newaxis]     # newaxis로 차원 증가함.
newaxis_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 배열 연결하기
행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하는 방법  
- `hstack`: 행의 수가 같은 두 개 이상의 배열을 연결  
- `vstack`: 열의 수가 같은 두 개 이상의 배열을 연결  
- `dstack`: 행과 열의 수가 같은 두 개 이상의 배열을 연결  
- `stack`  : dstack 확장 기능으로 행과 열의 수가 같은 두 개 이상의 배열을 연결, 단, 연결 축을 개발자가 직접 지정  
- `r_`  : 배열의 요소를 연결, 메서드 인자를 `[]`에 전달함  
- `c_` : 행끼리 연결, 최소 2차원의 배열로 연결  
- `tile`: 하나의 배열을 여러번 반복하여 연결

In [264]:
zeros_array = np.zeros((3, 4))  # zeros이므로 모두 0. 으로 초기화
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [265]:
ones_array = np.ones((3, 2))    # ones 이므로 모두 1. 으로 초기화
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

- `hstack`: 행의 수가 같은 두 개 이상의 배열을 연결  

In [266]:
hstack_array = np.hstack((zeros_array, ones_array))
hstack_array

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

- `vstack`: 열의 수가 같은 두 개 이상의 배열을 연결 

In [267]:
zeros_array = np.zeros((3, 4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [268]:
ones_array = np.ones((2, 4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [269]:
vstack_array = np.vstack([zeros_array, ones_array])
vstack_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- `dstack`: 행과 열의 수가 같은 두 개 이상의 배열을 연결  

In [270]:
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [271]:
ones_array = np.ones((3, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [272]:
dstack_array = np.dstack([zeros_array, ones_array])
dstack_array

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

- `stack`  : dstack 확장 기능으로 행과 열의 수가 같은 두 개 이상의 배열을 연결, 단, 연결 축을 개발자가 직접 지정 

In [273]:
zeros_array, ones_array

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [274]:
stack_array = np.stack([zeros_array, ones_array])
stack_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [275]:
stack_array = np.stack([zeros_array, ones_array], axis= 1)
stack_array

array([[[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]]])

- `r_`  : 배열의 요소를 연결, 메서드 인자를 `[]`에 전달함  
- `c_` : 행끼리 연결, 최소 2차원의 배열로 연결  

In [276]:
zeros_array, ones_array

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [277]:
r_araay = np.r_[zeros_array, ones_array]
r_araay # r_ : zeros 와 ones를 서로 붙인다고 생각.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [278]:
c_array = np.c_[zeros_array, ones_array]
c_array     # zeros 와 ones를 가로로 붙인다고 생각.

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

- `tile`: 하나의 배열을 여러번 반복하여 연결

In [279]:
tile_array = np.tile(zeros_array, 2)
tile_array      # tile: 반복.

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [280]:
tile_array = np.tile(zeros_array, (3, 2))
tile_array      

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [281]:
zeros_array = np.zeros((3, 3))
ones_array = np.ones((3, 2))
hstack_array = np.hstack([zeros_array, ones_array])

arage_array = np.arange(10, 151, 10)
reshape_array = arage_array.reshape(3, 5)
vstack_array = np.vstack([hstack_array, reshape_array])

tile_array = np.tile(vstack_array, (2, 1))
tile_array

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

### 2차원 그리드 포인트 생성
좌표값의 쌍(그리드 포인트)을 생성하는 메서드 `meshgird`함수로 x축과 y축의 점들로 사각형의  
영역을 나타내는 조합을 생성

In [282]:
x = np.arange(3)
x

array([0, 1, 2])

In [283]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [284]:
X, Y = np.meshgrid(x, y)
X, Y

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]))

In [285]:
[list(zip(x, y)) for x, y in zip(X, Y)]
list(zip(X, Y))

[(array([0, 1, 2]), array([0, 0, 0])),
 (array([0, 1, 2]), array([1, 1, 1])),
 (array([0, 1, 2]), array([2, 2, 2])),
 (array([0, 1, 2]), array([3, 3, 3])),
 (array([0, 1, 2]), array([4, 4, 4]))]

### 벡터화 연산
numpy 배열은 반복문을 쓰지않고 배열에 대하여 벡터 연산을 할 수 있음

In [286]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [287]:
%%time
z = np.zeros_like(x)
for index in range(len(x)):
    z[index] = x[index] + y[index]

CPU times: total: 0 ns
Wall time: 1.99 ms


In [288]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [289]:
x = np.arange(5)
y = np.arange(10, 15)
z = np.arange(5)
x, y, z

(array([0, 1, 2, 3, 4]), array([10, 11, 12, 13, 14]), array([0, 1, 2, 3, 4]))

In [290]:
np.all(x == y)

False

In [291]:
np.all(x == z)

True

In [292]:
np.all(x <= y)

True

In [293]:
x

array([0, 1, 2, 3, 4])

In [294]:
x * 10

array([ 0, 10, 20, 30, 40])

In [295]:
10 ** x

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [296]:
x ** 10

array([      0,       1,    1024,   59049, 1048576], dtype=int32)

### 브로드 캐스팅
차원이 서로 다른 배열을 연산하는 기능, 부족한 차원에 대하여 반복 확장하여 큰 배열의 크기에 맞춘 후 연산을 진행

In [297]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [298]:
x + 1

array([1, 2, 3, 4, 5])

In [299]:
x - 1

array([-1,  0,  1,  2,  3])

In [300]:
x = np.arange(15)
x = x.reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [301]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [302]:
x + y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

In [303]:
y = np.arange(3)
y = y.reshape(3, 1)
y

array([[0],
       [1],
       [2]])

In [304]:
x+y

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16]])

### 차원 축소 연산
배열의 하나의 행을 하나의 집합으로 보고 그 집합에 대한 집계 처리 결과로 새로운 값을 반환하여 배열을 생성

In [305]:
x = np.arange(10)   # 1차원
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [306]:
x = np.arange(10)
x = x.reshape(2, 5) # 2차원
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [307]:
print(x.max())
x.min()

9


0

In [308]:
x.mean()    # 평균값

4.5

In [309]:
np.median(x)

4.5

In [310]:
x.sum(axis = 0)         # 행을 따로 분리 정렬

array([ 5,  7,  9, 11, 13])

In [311]:
x.sum(axis = 1)         # 열을 따로 분리 정렬

array([10, 35])

### 정렬
`sort` 메서드로 배열을 정렬 할 수 있음
`axis` 매개변수로 정렬 기준을 정할 수 있음
`axis = 0`: 행을 따로 분리하여 정렬
`axis = 1`: 열을 따로 분리하여 정렬
`axis`를 지정하지 않으면 가장 나중 차원을 기준으로 정렬

In [312]:
x = np.array([
    [5, 2, 7, 4],
    [11, 8, 6, 5],
    [8, 5, 11, 2]
    ])
x

array([[ 5,  2,  7,  4],
       [11,  8,  6,  5],
       [ 8,  5, 11,  2]])

In [313]:
x.sort()
x

array([[ 2,  4,  5,  7],
       [ 5,  6,  8, 11],
       [ 2,  5,  8, 11]])

In [314]:
x.sort(axis = 1)
x

array([[ 2,  4,  5,  7],
       [ 5,  6,  8, 11],
       [ 2,  5,  8, 11]])

In [315]:
x.sort(axis=0)
x

array([[ 2,  4,  5,  7],
       [ 2,  5,  8, 11],
       [ 5,  6,  8, 11]])

In [316]:
np.argsort(x, axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]], dtype=int64)

실수로 이루어진 3 x 3 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.  

1. 전체의 최댓값  
2. 각 행의 합  
3. 각 행의 최댓값  
4. 각 열의 평균  
5. 각 열의 최솟값  

In [317]:
y = np.array([
    [5, 11, 12],
    [0, 18, 22],
    [8, 2, 7]
    ])
y

array([[ 5, 11, 12],
       [ 0, 18, 22],
       [ 8,  2,  7]])

In [318]:
y.sort()
y

array([[ 5, 11, 12],
       [ 0, 18, 22],
       [ 2,  7,  8]])

In [319]:
np.sort(y, axis=1)
y

array([[ 5, 11, 12],
       [ 0, 18, 22],
       [ 2,  7,  8]])

In [320]:
np.sort(y, axis=0)
y

array([[ 5, 11, 12],
       [ 0, 18, 22],
       [ 2,  7,  8]])

In [321]:
# 1
print(y.max())
# 2
print(y.sum(axis=1))
# 3
print(y.max(axis=1))
# 4
print(y.mean(axis=0))
# 5
print(y.min(axis=0))


22
[28 40 17]
[12 22  8]
[ 2.33333333 12.         14.        ]
[0 7 8]


### Numpy 배열 통계 연산
- 데이터 개수 구하기: `len()`내장 함수
- 표본 평균: `mean()`메서드
- 표본 분산: `var()` 메서드
- 표본 표준편차: `std()`메서드
- 최대, 최소: `max()`, `min()`메서드
- 중앙값: `median()` 메서드
- 사분위수: `percentile()` 메서드

In [322]:
samples = np.array([9, 2, 4, 20, 24, 2, 23, 92, 24, -23])
samples

array([  9,   2,   4,  20,  24,   2,  23,  92,  24, -23])

In [323]:
samples_volume = len(samples)
samples_volume

10

In [324]:
sample_mean = samples.mean()
sample_mean

17.7

In [325]:
# 표본 평균 mean 다른 방법
sample_mean = np.mean(samples)
sample_mean

17.7

In [326]:
# var: 분산
sample_variance = samples.var()
sample_variance

804.61

In [327]:
# 표준편차
sample_standard = samples.std()
sample_standard     

28.365648238670662

In [328]:
# 표준편차 다른 방법
sample_standard = np.std(samples)
sample_standard     

28.365648238670662

In [329]:
# 최대 최소
sample_max = samples.max()
sample_max

92

In [330]:
sample_min = samples.min()
sample_min

-23

In [331]:
# 중앙값  (중앙값은 np. 으로만 찍어야 나옴.)
sample_median = np.median(samples)
sample_median

14.5

In [332]:
# 사분위수
sample_Oper = np.percentile(samples, 0)
sample_Oper

-23.0

In [333]:
# 사분위수
sample_Oper = np.percentile(samples, 25)    # samples에서 1/4 위치에 있는 것이므로 ([9, 2, 4, 20, 24, 2, 23, 92, 24, -23])에서 1/4위치는 2, 4 사이인 2.5
sample_Oper

2.5

In [334]:
# 사분위수
sample_Oper = np.percentile(samples, 50) # samples에서의 중앙값 이므로, ([9, 2, 4, 20, 24, 2, 23, 92, 24, -23])에서 24, 2 의 평균을 구하면 된다.
sample_Oper

14.5

In [335]:
# 사분위수
sample_Oper = np.percentile(samples, 75)
sample_Oper

23.75

In [336]:
# 사분위수
sample_Oper = np.percentile(samples, 100)
sample_Oper

92.0

### 난수 생성에 필요한 시드 설정
numpy 패키지에 있는 `seed()` 메서드에 매개변수로 난수 생성시 필요한 시드를 설정 함  
`seed()`를 사용하면 무작위의 결과를 특정한 값으로 고정할 수 있다.

In [367]:
np.random.seed(0)

In [371]:
random_array = np.random.rand(10)
random_array

array([0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
       0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ])

### 데이터 순서를 바꾸기
numpy 패키지의 random 하위 패키지의 `shuffle()`메서드로 배열을 임의 순서로 변경 가능

In [338]:
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [339]:
shuffle_array = np.random.shuffle(range_array)  # np.random.shuffle(range_array) 로 대체 가능.
range_array     # 보이는대로 랜덤이니까 랜덤으로 순서가 바뀜.

array([1, 6, 2, 5, 7, 8, 9, 0, 3, 4])

### 데이터 샘플링
모집단 배열에 표본으로 사용할 표본 집단 배열을 무작위로 선택하는 방법  
numpy 패키지의 random 하위패키지의 `choice(모집단배열, 표본크기, 중복선택여부, 각요소의 선택확률 배열)` 메서드로 사용 가능

In [340]:
population_array = np.arange(10)
population_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [341]:
sample_array = np.random.choice(population_array, 5)
sample_array

array([1, 8, 4, 1, 3])

In [342]:
sample_array = np.random.choice(population_array, 5, replace=False) # True 는 중복값 허용, False는 중복값 허용하지 않음.
sample_array

array([7, 0, 9, 2, 4])

In [343]:
probability_array = [0.1, 0.05, 0.05, 0, 0.15, 0.25, 0.1, 0.05, 0.05, 0.2]
sample_array = np.random.choice(population_array, 10000, p = probability_array)
sample_array        
# probability_array에[0.1, 0.05, 0.05, 0, 0.15, 0.25, 0.1, 0.05, 0.05, 0.2] 배열이 있고, 
# sample_array에 np.random.choice 로 무작위로 고르게 한다. 범위는 ( 1행에 있는 probability_array이고, 사이즈는 10000 으로
# 10000개의 배열을 만든다. p = probability_array 는 probability_array에 있는 배열의 확률로 한다. )
# samples = np.array([9, 2, 4, 20, 24, 2, 23, 92, 24, -23])

array([9, 1, 4, ..., 6, 5, 4])

In [344]:
# sample_array = np.random.choice(population_array, 12, replace=False)
# sample_array

In [345]:
probability_array = [0.1, 0.05, 0.05, 0, 0.15, 0.25, 0.1, 0.05, 0.05, 0.2]
sample_array = np.random.choice(population_array, 10000, p = probability_array)
sample_array

array([5, 5, 7, ..., 5, 7, 5])

### 난수 배열 생성
- `rand()`: 0과 1사이의 균일 분포를 따르는 난수 배열 생성  
- `randn()`: 표준 정규 분포를 따르는 난수 배열 생성  
- `randint(low, high = 정수, size = 정수 혹은 튜플)`: 지정한 범위의 정수의 균일 분포를 따르는 난수 배열 생성

In [346]:
rand_array = np.random.rand(10)
rand_array

array([0.9660376 , 0.23062789, 0.36418595, 0.76596407, 0.15643316,
       0.02106394, 0.19569718, 0.03523948, 0.61679209, 0.83678492])

In [347]:
randn_array = np.random.randn(10)
randn_array

array([-0.48367119, -2.68954717, -0.13811111, -0.68263331, -0.19942057,
        0.00893473,  0.12159043,  0.26723688,  1.07357393, -0.45226255])

In [348]:
randint_array = np.random.randint(10)       # randint()는 사이즈를 지정 하지 않으면 그냥 하나의 정수가 랜덤으로 나옴
randint_array

3

In [349]:
randint_array = np.random.randint(10, size=10)
randint_array

array([6, 1, 6, 3, 6, 3, 6, 3, 1, 0])

In [350]:
randint_array = np.random.randint(10, high=20, size=10) # 10, high20(10~19) 사이즈 10개의 랜덤정수를 출력.
randint_array

array([10, 15, 15, 19, 16, 13, 13, 10, 14, 16])

In [351]:
randint_array = np.random.randint(10, high=20, size=(3,5))  # size(x, y)= (행, 열)
randint_array

array([[14, 15, 17, 16, 16],
       [10, 19, 13, 13, 11],
       [12, 19, 19, 18, 12]])

### 정수 데이터 카운팅
배열의 요소가 정수이면 `unique()`메서드나 `bincount()` 메서드로 간단하게 분석할 수 있음

In [352]:
# probability_array = [0.1, 0.05, 0.05, 0, 0.15, 0.25, 0.1, 0.05, 0.05, 0.2]
# sample_array = np.random.choice(population_array, 10000, p = probability_array)
# sample_array

In [353]:
sample_array

array([5, 5, 7, ..., 5, 7, 5])

In [354]:
analysis_array = np.unique(sample_array)    # 유니크로 sample_array가 지닌 중보값 제거.
analysis_array

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [355]:
analysis_array = np.unique(sample_array, return_counts=True)    # return_counts=true 로 갯수 확인.
analysis_array  # 즉 0이 중복된 값은 1013개, 1이 중복된 값은 513개, 4가 중복된 값이 504개, ... 9가 중복된 값은 1987개 란 뜻.

(array([0, 1, 2, 4, 5, 6, 7, 8, 9]),
 array([ 976,  541,  510, 1560, 2377,  974,  502,  508, 2052], dtype=int64))

In [356]:
analysis_array = np.bincount(sample_array, minlength=10)    # minelength= 10  이면 0~9의 숫자중에 존재하지 않는 값은 0으로 출력된다.
analysis_array  # np.uniqe (sample_array)에 0~9중 3이 빠져 있으므로 3자리의 위치에 0이 출력된다. 나머지 존재하는 값들은 그 중복하는 갯수가 출력된다.

array([ 976,  541,  510,    0, 1560, 2377,  974,  502,  508, 2052],
      dtype=int64)

1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
2. 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.

In [357]:
# 1.
coin_simulation = np.random.randint(2, size=10) 
coin_simulation


array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0])

In [358]:
# 2.
dice_simulation = np.random.randint(1, high=7, size=100)
dice_simulation_mean = dice_simulation.mean()
dice_simulation_mean

3.51

파이썬으로 다음 연산을 수행한다.

가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [359]:
price = 10000

variation_ranges = (np.random.randn(250) / 100) + 1
stock_price = []

for ratio in variation_ranges:
    price = round(price * round(ratio, 4))
    stock_price.append(price)

stock_price_array = np.array(stock_price)
stock_price_array
        

array([ 9775,  9735,  9719,  9460,  9270,  9267,  9318,  9371,  9438,
        9375,  9330,  9252,  9359,  9335,  9356,  9267,  9256,  9206,
        9281,  9363,  9387,  9331,  9304,  9276,  9410,  9364,  9394,
        9434,  9430,  9470,  9558,  9553,  9547,  9461,  9493,  9556,
        9655,  9562,  9528,  9540,  9501,  9503,  9363,  9364,  9431,
        9415,  9468,  9530,  9515,  9556,  9438,  9489,  9673,  9588,
        9485,  9209,  9238,  9161,  9100,  9056,  9115,  9195,  9157,
        9108,  9072,  9035,  8988,  8950,  8985,  8848,  9018,  8993,
        8980,  8863,  8830,  8768,  8793,  8868,  8773,  8716,  8685,
        8747,  8774,  8922,  8876,  8831,  8800,  8860,  8848,  8806,
        8877,  8871,  8816,  8774,  8782,  8800,  8779,  8819,  8726,
        8744,  8764,  8684,  8634,  8590,  8654,  8869,  9076,  9169,
        9295,  9302,  9162,  9090,  9093,  9054,  9097,  9243,  9265,
        9260,  9264,  9273,  9388,  9273,  9372,  9374,  9493,  9487,
        9516,  9490,